# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris Note
email: kshke0723@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  開發的大小事.
baseurl: / # the subpath of your site, e.g. /blog
url: "http://chrislutw.github.io" # the base hostname & protocol for your site

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Build settings
markdown: kramdown

author:
  name:           'Chris Lu'
  url:            https://chrislutw.github.io
